name: glp
channels:
  - bioconda
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python
  - ipykernel
  - numpy
  - scipy
  - xarray
  - dask
  - matplotlib
  - torchinfo
  - ipywidgets
  - pytorch
  - torchvision
  - torchaudio
  - pytorch::pytorch-cuda=13.3.*
